import { useMemo, useState } from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AnimatedMetric } from "@/components/animated-metric";
import { useCarbon } from "@/lib/carbon-context";
import { sumRange } from "@/lib/carbon";

const C = { ink: "#173B4A", muted: "#4C6771", surface: "#F8FCFF", border: "#CFE7F5", coral: "#E56B50", mint: "#CDEFE4", blue: "#74BFE0" };
const ranges = { Week: [42, 58, 48, 72, 56, 66, 51], Month: [46, 58, 40, 64, 52, 69, 48, 62, 45, 58, 50, 64], Year: [54, 48, 61, 44, 57, 49, 52, 43, 47, 42, 39, 35] };

export default function HistoryScreen() {
  const { activities } = useCarbon();
  const [range, setRange] = useState<keyof typeof ranges>("Week");
  const total = useMemo(() => sumRange(activities), [activities]);
  const bars = ranges[range];
  const latest = range === "Week" ? total.high * 7 : range === "Month" ? total.high * 30 : total.high * 365;
  return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
    <Text style={styles.eyebrow}>YOUR HISTORY</Text><Text style={styles.title}>See the signal over time.</Text><Text style={styles.subtitle}>Progress is a pattern, not a single perfect day. Compare your footprint across useful horizons.</Text>
    <View style={styles.segment}>{(Object.keys(ranges) as (keyof typeof ranges)[]).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.segmentItem, range === item && styles.segmentActive]}><Text style={[styles.segmentText, range === item && styles.segmentTextActive]}>{item}</Text></Pressable>)}</View>
    <View style={styles.hero}><Text style={styles.heroLabel}>{range.toUpperCase()} ESTIMATE</Text><View style={styles.metricLine}><AnimatedMetric value={latest} suffix=" kg CO2e" style={styles.heroMetric} /></View><Text style={styles.heroCopy}>{activities.length} logged activities · ranges preserve uncertainty</Text></View>
    <View style={styles.card}><View style={styles.cardHeader}><Text style={styles.cardTitle}>{range} pattern</Text><Text style={styles.trend}>↓ 12% vs prior</Text></View><View style={styles.chart}>{bars.map((height, index) => <View key={`${range}-${index}`} style={styles.column}><View style={[styles.bar, { height: `${height}%`, backgroundColor: index === bars.length - 1 ? C.coral : index % 3 === 0 ? C.blue : C.mint }]} /><Text style={styles.label}>{range === "Week" ? ["M", "T", "W", "T", "F", "S", "S"][index] : range === "Month" ? `${index + 1}` : ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"][index]}</Text></View>)}</View><Text style={styles.chartNote}>Your latest period is highlighted. Keep looking for the smallest repeatable improvement.</Text></View>
    <View style={styles.insight}><Text style={styles.insightLabel}>A useful question</Text><Text style={styles.insightTitle}>What changed when the line moved?</Text><Text style={styles.insightCopy}>Open Time Machine to replay two choices and connect a lower week to an action you can repeat.</Text></View>
    <Text style={styles.sectionTitle}>Climate, made clearer</Text><Pressable onPress={() => void Linking.openURL("https://climate.nasa.gov/what-is-climate-change/")} style={styles.newsCard}><Text style={styles.newsSource}>NASA CLIMATE · EXPLAINER</Text><Text style={styles.newsTitle}>What is climate change?</Text><Text style={styles.newsCopy}>A clear guide to how greenhouse gases warm the planet and why daily choices fit into a bigger system.</Text><Text style={styles.newsLink}>Read the source ↗</Text></Pressable><Pressable onPress={() => void Linking.openURL("https://www.unep.org/resources/emissions-gap-report-2024")} style={styles.newsCard}><Text style={styles.newsSource}>UNEP · GLOBAL UPDATE</Text><Text style={styles.newsTitle}>The emissions gap, in plain language</Text><Text style={styles.newsCopy}>Understand why the speed of reducing emissions matters, without turning the issue into guilt or noise.</Text><Text style={styles.newsLink}>Read the source ↗</Text></Pressable>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 32, gap: 16 }, eyebrow: { color: C.coral, fontSize: 11, letterSpacing: 1.5, fontWeight: "800" }, title: { color: C.ink, fontSize: 29, lineHeight: 34, fontWeight: "800", marginTop: 4 }, subtitle: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: -6 }, sectionTitle: { color: C.ink, fontSize: 17, fontWeight: "800" }, segment: { flexDirection: "row", backgroundColor: "#DCEEF7", padding: 4, borderRadius: 14 }, segmentItem: { flex: 1, alignItems: "center", paddingVertical: 9, borderRadius: 10 }, segmentActive: { backgroundColor: C.surface }, segmentText: { color: C.muted, fontSize: 12, fontWeight: "700" }, segmentTextActive: { color: C.ink }, hero: { backgroundColor: C.ink, borderRadius: 24, padding: 20 }, heroLabel: { color: C.mint, fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, metricLine: { flexDirection: "row", alignItems: "baseline" }, heroMetric: { color: "#FFF", fontSize: 31, fontWeight: "800", marginTop: 12 }, heroCopy: { color: "#C5D3CB", fontSize: 12, marginTop: 6 }, card: { backgroundColor: C.surface, borderRadius: 20, padding: 17, borderWidth: 1, borderColor: C.border }, cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, cardTitle: { color: C.ink, fontSize: 16, fontWeight: "800" }, trend: { color: "#287A68", fontSize: 11, fontWeight: "800" }, chart: { height: 150, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingTop: 22, marginTop: 8 }, column: { height: "100%", alignItems: "center", justifyContent: "flex-end", gap: 7, flex: 1 }, bar: { width: 16, minHeight: 18, borderRadius: 8 }, label: { color: C.muted, fontSize: 9, fontWeight: "800" }, chartNote: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 12 }, insight: { backgroundColor: "#EAF7FF", borderRadius: 18, padding: 17 }, newsCard: { backgroundColor: "#F8FCFF", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: C.border }, newsSource: { color: C.coral, fontSize: 9, letterSpacing: 1.1, fontWeight: "900" }, newsTitle: { color: C.ink, fontSize: 15, fontWeight: "800", marginTop: 6 }, newsCopy: { color: C.muted, fontSize: 11, lineHeight: 17, marginTop: 5 }, newsLink: { color: C.blue, fontSize: 11, fontWeight: "800", marginTop: 10 }, insightLabel: { color: C.coral, fontSize: 10, letterSpacing: 1, fontWeight: "800" }, insightTitle: { color: C.ink, fontSize: 16, fontWeight: "800", marginTop: 6 }, insightCopy: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 5 } });
