import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { CelebrationPopup } from "@/components/celebration-popup";
import { haptic } from "@/lib/haptics";

const C = { ink: "#173B4A", muted: "#4C6771", surface: "#F8FCFF", border: "#CFE7F5", coral: "#E56B50", mint: "#CDEFE4" };
const choices = [{ label: "Walk 2 km", impact: "Low-carbon choice", correct: true }, { label: "Drive alone", impact: "Higher transport signal", correct: false }, { label: "Take a short flight", impact: "Highest transport signal", correct: false }];
export default function LearnScreen() { const [picked, setPicked] = useState<number | null>(null); const [showWin, setShowWin] = useState(false); const choose = (index: number) => { setPicked(index); haptic.selection(); if (choices[index].correct) { haptic.success(); setShowWin(true); } }; return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CARBON PLAYGROUND</Text><Text style={styles.title}>Learn by choosing the next move.</Text><Text style={styles.subtitle}>A 30-second mini-game for building climate intuition. There is no score pressure—just a clearer signal.</Text><View style={styles.streak}><Text style={styles.streakLabel}>TODAY&apos;S CLIMATE QUEST</Text><Text style={styles.streakTitle}>Which trip creates the lightest footprint?</Text><Text style={styles.streakHint}>Tap one answer to reveal the why.</Text></View><View style={styles.choices}>{choices.map((choice, index) => <Pressable key={choice.label} onPress={() => choose(index)} style={({ pressed }) => [styles.choice, picked === index && (choice.correct ? styles.correct : styles.wrong), pressed && { transform: [{ scale: 0.98 }], opacity: 0.85 }]}><View style={[styles.choiceDot, picked === index && (choice.correct ? styles.correctDot : styles.wrongDot)]}><Text style={styles.choiceNumber}>{index + 1}</Text></View><View style={styles.choiceBody}><Text style={styles.choiceTitle}>{choice.label}</Text>{picked === index && <Text style={styles.choiceImpact}>{choice.correct ? "✓ " : "! "}{choice.impact}</Text>}</View></Pressable>)}</View><View style={styles.tip}><Text style={styles.tipLabel}>CARBONWISE PRINCIPLE</Text><Text style={styles.tipText}>Small choices compound. The best choice is the one you can repeat.</Text></View></ScrollView><CelebrationPopup visible={showWin} eyebrow="CLIMATE WIN" title="Good instinct." body="You chose the lightest trip. CarbonWise turns this kind of intuition into an everyday habit." actionLabel="Play again" onClose={() => { setShowWin(false); setPicked(null); }} /></ScreenContainer>; }
const styles = StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 32, gap: 16 }, eyebrow: { color: C.coral, fontSize: 11, letterSpacing: 1.5, fontWeight: "800" }, title: { color: C.ink, fontSize: 29, lineHeight: 34, fontWeight: "800", marginTop: 4 }, subtitle: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: -6 }, streak: { backgroundColor: C.ink, borderRadius: 22, padding: 19 }, streakLabel: { color: C.mint, fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, streakTitle: { color: "#FFF", fontSize: 22, lineHeight: 28, fontWeight: "800", marginTop: 10 }, streakHint: { color: "#C5D3CB", fontSize: 12, marginTop: 7 }, choices: { gap: 10 }, choice: { backgroundColor: C.surface, borderRadius: 17, borderWidth: 1, borderColor: C.border, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, correct: { borderColor: "#82C9B5", backgroundColor: "#F0FBF7" }, wrong: { borderColor: "#F0B7AB", backgroundColor: "#FFF6F3" }, choiceDot: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#EAF7FF", alignItems: "center", justifyContent: "center" }, correctDot: { backgroundColor: C.mint }, wrongDot: { backgroundColor: "#F8DAD3" }, choiceNumber: { color: C.ink, fontWeight: "900" }, choiceBody: { flex: 1 }, choiceTitle: { color: C.ink, fontSize: 15, fontWeight: "800" }, choiceImpact: { color: C.muted, fontSize: 11, marginTop: 4 }, tip: { backgroundColor: "#EAF7FF", borderRadius: 18, padding: 16 }, tipLabel: { color: C.coral, fontSize: 10, letterSpacing: 1, fontWeight: "800" }, tipText: { color: C.ink, fontSize: 15, lineHeight: 21, fontWeight: "700", marginTop: 6 } });
