import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useCarbon } from "@/lib/carbon-context";
import { sumRange } from "@/lib/carbon";

const C = { ink: "#17211F", muted: "#68736E", surface: "#FFFDFC", border: "#E6E0D8", coral: "#E56B50", mint: "#B9D9C5", amber: "#E8B86A" };
function Tag({ children, tone = "mint" }: { children: string; tone?: "mint" | "amber" }) { return <View style={[styles.tag, { backgroundColor: tone === "mint" ? "#DDF0E4" : "#F8E6C8" }]}><Text style={styles.tagText}>{children}</Text></View>; }
export default function TwinScreen() { const { activities } = useCarbon(); const total = sumRange(activities); const transport = activities.filter((a) => a.category === "transport").reduce((s, a) => s + a.quantity, 0); const measured = activities.filter((a) => a.confidence === "HIGH").length; return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CARBON TWIN</Text><Text style={styles.title}>A clearer picture of your week.</Text><Text style={styles.subtitle}>Your twin is built from what you log — not assumptions about who you should be.</Text><View style={styles.hero}><Text style={styles.heroLabel}>CURRENT WEEKLY RANGE</Text><Text style={styles.heroMetric}>{(total.low * 5).toFixed(1)}–{(total.high * 5).toFixed(1)} <Text style={styles.unit}>kg CO2e</Text></Text><Text style={styles.heroCopy}>Based on {activities.length} logged activities</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Your pattern summary</Text><View style={styles.pattern}><View style={[styles.patternIcon, { backgroundColor: "#F4E9E3" }]}><Text style={styles.patternIconText}>↗</Text></View><View style={styles.patternBody}><Text style={styles.patternTitle}>Transport leads at ~{transport} km/week</Text><Text style={styles.patternCopy}>Short trips are the most changeable part of your current twin.</Text></View><Tag tone="mint">Measured</Tag></View><View style={styles.pattern}><View style={[styles.patternIcon, { backgroundColor: "#E8F0E8" }]}><Text style={styles.patternIconText}>◌</Text></View><View style={styles.patternBody}><Text style={styles.patternTitle}>Food is a steady background signal</Text><Text style={styles.patternCopy}>Meal estimates are category-based, so the range is wider.</Text></View><Tag tone="amber">Estimated</Tag></View><View style={styles.pattern}><View style={[styles.patternIcon, { backgroundColor: "#F8E6C8" }]}><Text style={styles.patternIconText}>⌁</Text></View><View style={styles.patternBody}><Text style={styles.patternTitle}>Home energy needs more data</Text><Text style={styles.patternCopy}>One more week of readings will narrow this estimate.</Text></View><Tag tone="amber">Assumed</Tag></View></View><View style={styles.note}><Text style={styles.noteTitle}>{measured > 0 ? "Your twin is getting sharper." : "Start with one measured activity."}</Text><Text style={styles.noteCopy}>Confidence is shown on every estimate so you can see what CarbonWise knows and what it is still learning.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 32, gap: 16 }, eyebrow: { color: C.coral, fontSize: 11, letterSpacing: 1.5, fontWeight: "800" }, title: { color: C.ink, fontSize: 29, lineHeight: 34, fontWeight: "800", marginTop: 4 }, subtitle: { color: C.muted, fontSize: 14, lineHeight: 20, marginTop: -6 }, hero: { backgroundColor: C.ink, borderRadius: 24, padding: 20, marginTop: 4 }, heroLabel: { color: C.mint, fontSize: 11, letterSpacing: 1.2, fontWeight: "800" }, heroMetric: { color: "#FFF", fontSize: 34, fontWeight: "800", marginTop: 12 }, unit: { color: "#C5D3CB", fontSize: 14 }, heroCopy: { color: "#C5D3CB", fontSize: 12, marginTop: 5 }, card: { backgroundColor: C.surface, borderRadius: 20, padding: 17, borderWidth: 1, borderColor: C.border }, cardTitle: { color: C.ink, fontSize: 17, fontWeight: "800", marginBottom: 4 }, pattern: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "#F0EBE5" }, patternIcon: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center" }, patternIconText: { color: C.ink, fontSize: 18, fontWeight: "800" }, patternBody: { flex: 1 }, patternTitle: { color: C.ink, fontSize: 13, fontWeight: "800" }, patternCopy: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, tag: { borderRadius: 20, paddingHorizontal: 8, paddingVertical: 5 }, tagText: { color: C.ink, fontSize: 9, fontWeight: "800" }, note: { backgroundColor: "#F4E9E3", borderRadius: 18, padding: 16 }, noteTitle: { color: C.ink, fontWeight: "800", fontSize: 14 }, noteCopy: { color: C.muted, fontSize: 12, lineHeight: 17, marginTop: 5 } });
